---
title: "A graphical summary of your random forest"
author: "randomForestExplainer"
date: `r as.character(format(Sys.Date(), format="%B %d, %Y"))`
output: 
    html_document:
        toc: true
        toc_float: true
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, echo = FALSEE)
```

```{r}
min_depth_frame <- min_depth_distribution(forest)
importance_frame <- measure_importance(forest)
# interactions_frame <- min_depth_interactions(forest, vars)
```

## Details of your forest

```{r}
forest
```

## Distribution of minimal depth

```{r}
plot_min_depth_distribution(min_depth_frame)
```

## Multi-way importance plot

```{r}
if(forest$type == "regression"){
  size_measure <- "mse_increase"
} else {
  size_measure <- "accuracy_decrease"
}
plot_multi_way_importance(importance_frame, size_measure = size_measure)
```

## Compare different measures of importance

```{r}
plot_importance_ggpairs(importance_frame)
```

## Compare different rankings of variables

```{r}
plot_importance_rankings(importance_frame)
```

## Interactions: conditional minimal depth

```{r}
# plot_min_depth_interactions(interactions_frame)
```
